require 'inferno/dsl/oauth_credentials'
require_relative 'urls'
require_relative 'version'
require_relative 'report_generation_suite/exchange_bundle_group'

module CancerPathologyDataSharingTestKit
  class ReportGenerationSuite < Inferno::TestSuite
    include URLs
    id :cpds_report_generation
    title 'Cancer Pathology Data Sharing Report Generation Test Suite'
    short_title 'CPDS Report Generation Test Suite'
    description File.read(File.join(__dir__, 'docs', 'report_generation_suite_description.md'))
    links [
      {
        label: 'Report Issue',
        url: 'https://github.com/inferno-framework/cancer-pathology-data-sharing-test-kit/issues/'
      },
      {
        label: 'Open Source',
        url: 'https://github.com/inferno-framework/cancer-pathology-data-sharing-test-kit/'
      },
      {
        label: 'Download',
        url: 'https://github.com/inferno-framework/cancer-pathology-data-sharing-test-kit/releases'
      },
      {
        label: 'Implementation Guide',
        url: 'https://hl7.org/fhir/us/cancer-reporting/STU1.0.1/'
      }
    ]

    GENERAL_MESSAGE_FILTERS = [
      %r{Sub-extension url 'introspect' is not defined by the Extension http://fhir-registry\.smarthealthit\.org/StructureDefinition/oauth-uris},
      %r{Sub-extension url 'revoke' is not defined by the Extension http://fhir-registry\.smarthealthit\.org/StructureDefinition/oauth-uris},
      /Observation\.effective\.ofType\(Period\): .*vs-1:/, # Invalid invariant in FHIR v4.0.1
      /Observation\.effective\.ofType\(Period\): .*us-core-1:/, # Invalid invariant in US Core v3.1.1
      /Provenance.agent\[\d*\]: Constraint failed: provenance-1/, # Invalid invariant in US Core v5.0.1
      %r{Unknown Code System 'http://hl7.org/fhir/us/core/CodeSystem/us-core-tags'}, # Validator has an issue with this US Core 5 code system in US Core 6 resource # rubocop:disable Layout/LineLength
      %r{URL value 'http://hl7.org/fhir/us/core/CodeSystem/us-core-tags' does not resolve}, # Validator has an issue with this US Core 5 code system in US Core 6 resource # rubocop:disable Layout/LineLength
      /\A\S+: \S+: URL value '.*' does not resolve/,
      %r{Observation.component\[\d+\].value.ofType\(Quantity\): The code provided \(http://unitsofmeasure.org#L/min\) was not found in the value set 'Vital Signs Units'} # Known issue with the Pulse Oximetry Profile # rubocop:disable Layout/LineLength
    ].freeze
    VALIDATION_MESSAGE_FILTERS = GENERAL_MESSAGE_FILTERS

    fhir_resource_validator do
      igs 'hl7.fhir.us.cancer-reporting#1.0.1', 'hl7.fhir.us.core#5.0.1'
      message_filters = VALIDATION_MESSAGE_FILTERS

      exclude_message do |message|
        message_filters.any? { |filter| filter.match? message.message }
      end

      perform_additional_validation do |resource, _profile_url|
        ProvenanceValidator.validate(resource) if resource.instance_of?(FHIR::Provenance)
      end
    end

    resume_test_route :get, RESUME_PASS_PATH do |request|
      request.query_parameters['token']
    end
    resume_test_route :get, RESUME_FAIL_PATH, result: 'fail' do |request|
      request.query_parameters['token']
    end

    input :reports,
          title: 'Cancer Reports',
          description: 'A comma-Separated list of one or more FHIR Pathology Cancer Exchange Bundles ' \
                       'in JSON format generated by the system under test.',
          type: 'textarea'

    group from: :cpds_exchange_bundle_group
  end
end
