require_relative 'exchange_bundle/us_pathology_exchange_bundle/exchange_bundle_validation_test'
require_relative 'exchange_bundle/us_pathology_diagnostic_report/diagnostic_report_validation_test'
require_relative 'exchange_bundle/encounter/encounter_validation_test'
require_relative 'exchange_bundle/practitioner_role/practitioner_role_validation_test'
require_relative 'exchange_bundle/patient/patient_validation_test'
require_relative 'exchange_bundle/service_request/service_request_validation_test'
require_relative 'exchange_bundle/specimen/specimen_validation_test'

require_relative 'exchange_bundle/us_pathology_exchange_bundle/us_pathology_exchange_bundle_must_support_test'
require_relative 'exchange_bundle/patient/patient_must_support_test'
require_relative 'exchange_bundle/encounter/encounter_must_support_test'
require_relative 'exchange_bundle/us_pathology_diagnostic_report/us_pathology_diagnostic_report_must_support_test'
require_relative 'exchange_bundle/specimen/specimen_must_support_test'
require_relative 'exchange_bundle/service_request/service_request_must_support_test'
require_relative 'exchange_bundle/practitioner_role/practitioner_role_must_support_test'

require_relative '../data_absent_group'

module CancerPathologyDataSharingTestKit
  class ExchangeBundleGroup < Inferno::TestGroup
    title 'Exchange Bundle Group'
    id :cpds_exchange_bundle_group
    description %(
      # Background

      Theses tests verify that the system under test can generate conformant and complete cancer pathology reports
      following the requirements in the [Cancer Pathology Exchange Bundle profile](https://hl7.org/fhir/us/cancer-reporting/STU1.0.1/StructureDefinition-us-pathology-exchange-bundle.html).
      The tester will provide a list of Bundles generated by the system under test in the **Cancer Reports** input.
      Inferno will verify the conformance of each report and that the set of reports contains examples
      of all entry slices and each element that the Bundle profile and referenced profiles indicate must be supported.

      # Testing Methodology
      The provided Bundles are parsed and the individual resources within them are separated out
      and assigned a target profile based on their resource type.

      ## Profile Validation
      Each resource extracted from the bundles is expected to conform to
      its target profile. Each element in each resource is checked against
      teminology binding and cardinality requirements by the HL7 FHIR validator.

      While the [Cancer Pathology Exchange Bundle profile](https://hl7.org/fhir/us/cancer-reporting/STU1.0.1/StructureDefinition-us-pathology-exchange-bundle.html)
      slices entries by profile, Inferno checks that any instances of the profiled resource type
      conform to the indicated profile and there are not more instances of the profiled resource type than allowed
      by the slice cardinality. Specifically, each report must contain:
      - Exactly one Patient, which must conform to the [US Core Patient profile](http://hl7.org/fhir/us/core/STU5.0.1/StructureDefinition-us-core-patient.html).
      - At most one Encounter, which, if present, must conform to the [US Core Encounter profile](http://hl7.org/fhir/us/core/STU5.0.1/StructureDefinition-us-core-encounter.html).
      - Exactly one DiagnosticReport, which must conform to the [US Pathology Diagnostic Report profile](https://hl7.org/fhir/us/cancer-reporting/STU1.0.1/StructureDefinition-us-pathology-diagnostic-report.html).
      - One or more Specimens, each of which must conform to the [US Pathology Specimen profile](https://hl7.org/fhir/us/cancer-reporting/STU1.0.1/StructureDefinition-us-pathology-specimen.html).

      Additionally, each report may include:
      - Any number of ServiceRequests, each of which must conform to the [US Pathology Service Requests profile](https://hl7.org/fhir/us/cancer-reporting/STU1.0.1/StructureDefinition-us-pathology-service-request.html).
      - Any number of PractitionRoles, each of which must conform to the [US Pathology Related Practitioner Roles profile](https://hl7.org/fhir/us/cancer-reporting/STU1.0.1/StructureDefinition-us-pathology-related-practitioner-role.html).

      ## Must Support
      Must Support tests in this group check that each element of the target profile marked
      as "must support" is observed at least once across instances assigned to that profile.
      If one or more elements are not observed, the test will fail.
    )
    run_as_group

    group do
      title 'Report'
      test from: :cpds_exchange_bundle_validation_test
      test from: :cpds_v101_us_pathology_exchange_bundle_must_support_test
    end

    group do
      title 'Patient'
      test from: :cpds_patient_validation_test
      test from: :cpds_v101_us_core_v311_patient_must_support_test
    end

    group do
      title 'Encounter'
      test from: :cpds_encounter_validation_test
      test from: :cpds_v101_us_core_v311_encounter_must_support_test
    end

    group do
      title 'Diagnostic Report'
      test from: :cpds_diagnostic_report_validation_test
      test from: :cpds_v101_us_pathology_diagnostic_report_must_support_test
    end

    group do
      title 'Specimen'
      test from: :cpds_specimen_validation_test
      test from: :cpds_v101_specimen_must_support_test
    end

    group do
      title 'Service Request'
      test from: :cpds_service_request_validation_test
      test from: :cpds_v101_service_request_must_support_test
    end

    group do
      title 'Practitioner Role'
      test from: :cpds_practitioner_role_validation_test
      test from: :cpds_v101_practitioner_role_must_support_test
    end

    group from: :cpds_data_absent_reason
  end
end
